#:schema node_modules/wrangler/config-schema.json
name = "kosen-fest-2024-lp"
compatibility_date = "2024-10-04"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"
